# Generated by Django 4.2.5 on 2023-10-16 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_produit_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
