# Generated by Django 4.2.5 on 2023-10-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='shopifyLink',
            field=models.URLField(default="https:'//shopify.com"),
            preserve_default=False,
        ),
    ]
